### ISSUE TITLE
Reference Paper

### ISSUE THREAD

**Issue by hafidh561** [sunchang0124/dp_cgans#2]
Hello, I like your repository about generating synthetic data using gan and I want to make sure this reference paper. Is this repository officially implemented from [arXiv](https://arxiv.org/pdf/2206.13787.pdf)? Thank you for your attention

**Comment by sunchang0124** [comment]
Hi, thanks for your comment. Yes, indeed, this repository includes the code implementing the method from [the arXiv paper ](https://arxiv.org/pdf/2206.13787.pdf). The method is based on several important previous works on conditional GANS, and differential privacy tech. If you want to learn more details about these techniques, I suggest you also read references from our repo: https://github.com/sunchang0124/dp_cgans#%EF%B8%8F-references--further-reading. We included all the related methods and their code which inspired us to implement DP-CGANS. Thank you and please let me know if my answer is not sufficient or clear to you. -- Best, Chang
