### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vdemchenko3** [sunchang0124/dp_cgans#5]
Hello!

Thanks for making the DP-CGANS code open-sourced!

I tried running your python script example (with my own csv and the test one you provided), but kept running into segmentation faults.

I'm on a 32GB Macbook Pro and using python 3.9.  Are you aware of specific compute requirements needed to run this library?

**Comment by vdemchenko3** [comment]
Ended up being a Poetry issue that I resolved.

**Comment by sunchang0124** [comment]
Hi, glad to hear you solved the issue already! Please let us know if you encounter other questions. Thanks
